# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaccia\sezione_interfaccia.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1751, 1602)
        Form.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 659, 1582))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_sezione = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_sezione.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_sezione.setObjectName("verticalLayout_sezione")
        self.btn_sezioni_sezione = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_sezioni_sezione.setMinimumSize(QtCore.QSize(100, 32))
        self.btn_sezioni_sezione.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_sezioni_sezione.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    font:400 12pt \"Segoe UI\";\n"
"    color: rgb(255,255,255);\n"
"    padding-bottom: 4px;\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(50,50,50);\n"
"}\n"
"")
        self.btn_sezioni_sezione.setObjectName("btn_sezioni_sezione")
        self.verticalLayout_sezione.addWidget(self.btn_sezioni_sezione)
        self.frame_sezione = QtWidgets.QFrame(self.layoutWidget)
        self.frame_sezione.setStyleSheet("background-color: rgb(40,40,40);\n"
"border-radius:4px")
        self.frame_sezione.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sezione.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sezione.setObjectName("frame_sezione")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_sezione)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_sezione)
        self.frame_3.setStyleSheet("background-color: rgb(30,30,30);\n"
"border-radius:4px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setMinimumSize(QtCore.QSize(70, 0))
        self.label_20.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_20.setStyleSheet("font:400 12pt \"Segoe UI\";\n"
"color: rgb(255,255,255);\n"
"border: none")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.btn_sezione_rettangolo = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sezione_rettangolo.sizePolicy().hasHeightForWidth())
        self.btn_sezione_rettangolo.setSizePolicy(sizePolicy)
        self.btn_sezione_rettangolo.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_sezione_rettangolo.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_sezione_rettangolo.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(40,40,40);\n"
"}\n"
"")
        self.btn_sezione_rettangolo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("interfaccia\\icone/rettangolo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sezione_rettangolo.setIcon(icon)
        self.btn_sezione_rettangolo.setIconSize(QtCore.QSize(40, 40))
        self.btn_sezione_rettangolo.setObjectName("btn_sezione_rettangolo")
        self.horizontalLayout_5.addWidget(self.btn_sezione_rettangolo)
        self.btn_sezione_poligono = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sezione_poligono.sizePolicy().hasHeightForWidth())
        self.btn_sezione_poligono.setSizePolicy(sizePolicy)
        self.btn_sezione_poligono.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_sezione_poligono.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_sezione_poligono.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(40,40,40);\n"
"}\n"
"")
        self.btn_sezione_poligono.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("interfaccia\\icone/libero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sezione_poligono.setIcon(icon1)
        self.btn_sezione_poligono.setIconSize(QtCore.QSize(40, 40))
        self.btn_sezione_poligono.setObjectName("btn_sezione_poligono")
        self.horizontalLayout_5.addWidget(self.btn_sezione_poligono)
        self.btn_sezione_cerchio = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sezione_cerchio.sizePolicy().hasHeightForWidth())
        self.btn_sezione_cerchio.setSizePolicy(sizePolicy)
        self.btn_sezione_cerchio.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_sezione_cerchio.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_sezione_cerchio.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(40,40,40);\n"
"}\n"
"\n"
"")
        self.btn_sezione_cerchio.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("interfaccia\\icone/cerchio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sezione_cerchio.setIcon(icon2)
        self.btn_sezione_cerchio.setIconSize(QtCore.QSize(40, 40))
        self.btn_sezione_cerchio.setObjectName("btn_sezione_cerchio")
        self.horizontalLayout_5.addWidget(self.btn_sezione_cerchio)
        spacerItem = QtWidgets.QSpacerItem(284, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btn_sezione_accetta = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sezione_accetta.sizePolicy().hasHeightForWidth())
        self.btn_sezione_accetta.setSizePolicy(sizePolicy)
        self.btn_sezione_accetta.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_sezione_accetta.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_sezione_accetta.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"")
        self.btn_sezione_accetta.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("interfaccia\\icone/accetta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sezione_accetta.setIcon(icon3)
        self.btn_sezione_accetta.setIconSize(QtCore.QSize(30, 30))
        self.btn_sezione_accetta.setObjectName("btn_sezione_accetta")
        self.horizontalLayout_5.addWidget(self.btn_sezione_accetta)
        self.btn_sezione_cancella = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sezione_cancella.sizePolicy().hasHeightForWidth())
        self.btn_sezione_cancella.setSizePolicy(sizePolicy)
        self.btn_sezione_cancella.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_sezione_cancella.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_sezione_cancella.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"")
        self.btn_sezione_cancella.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("interfaccia\\icone/gomma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sezione_cancella.setIcon(icon4)
        self.btn_sezione_cancella.setIconSize(QtCore.QSize(32, 32))
        self.btn_sezione_cancella.setObjectName("btn_sezione_cancella")
        self.horizontalLayout_5.addWidget(self.btn_sezione_cancella)
        self.verticalLayout.addWidget(self.frame_3)
        self.tableView_sezione = QtWidgets.QTableView(self.frame_sezione)
        self.tableView_sezione.setMinimumSize(QtCore.QSize(0, 450))
        self.tableView_sezione.setMaximumSize(QtCore.QSize(16777215, 450))
        self.tableView_sezione.setStyleSheet("background-color: rgb(35,35,35);\n"
"border-radius:4px")
        self.tableView_sezione.setObjectName("tableView_sezione")
        self.verticalLayout.addWidget(self.tableView_sezione)
        self.verticalLayout_sezione.addWidget(self.frame_sezione)
        self.btn_sezioni_barre = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_sezioni_barre.setMinimumSize(QtCore.QSize(100, 32))
        self.btn_sezioni_barre.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_sezioni_barre.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    font:400 12pt \"Segoe UI\";\n"
"    color: rgb(255,255,255);\n"
"    padding-bottom: 4px;\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(50,50,50);\n"
"}\n"
"")
        self.btn_sezioni_barre.setObjectName("btn_sezioni_barre")
        self.verticalLayout_sezione.addWidget(self.btn_sezioni_barre)
        self.frame_barre = QtWidgets.QFrame(self.layoutWidget)
        self.frame_barre.setStyleSheet("background-color: rgb(40,40,40);\n"
"border-radius:4px")
        self.frame_barre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_barre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_barre.setObjectName("frame_barre")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_barre)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_barre)
        self.frame_4.setStyleSheet("background-color: rgb(30,30,30);\n"
"border-radius:4px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        self.label_21.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_21.setStyleSheet("font:400 12pt \"Segoe UI\";\n"
"color: rgb(255,255,255);\n"
"border: none")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.btn_barre_singole = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_barre_singole.sizePolicy().hasHeightForWidth())
        self.btn_barre_singole.setSizePolicy(sizePolicy)
        self.btn_barre_singole.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_barre_singole.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_barre_singole.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(40,40,40);\n"
"}\n"
"")
        self.btn_barre_singole.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("interfaccia\\icone/barra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_barre_singole.setIcon(icon5)
        self.btn_barre_singole.setIconSize(QtCore.QSize(40, 40))
        self.btn_barre_singole.setObjectName("btn_barre_singole")
        self.horizontalLayout_6.addWidget(self.btn_barre_singole)
        self.btn_barre_gruppi = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_barre_gruppi.sizePolicy().hasHeightForWidth())
        self.btn_barre_gruppi.setSizePolicy(sizePolicy)
        self.btn_barre_gruppi.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_barre_gruppi.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_barre_gruppi.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(40,40,40);\n"
"}\n"
"")
        self.btn_barre_gruppi.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("interfaccia\\icone/barre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_barre_gruppi.setIcon(icon6)
        self.btn_barre_gruppi.setIconSize(QtCore.QSize(40, 40))
        self.btn_barre_gruppi.setObjectName("btn_barre_gruppi")
        self.horizontalLayout_6.addWidget(self.btn_barre_gruppi)
        spacerItem1 = QtWidgets.QSpacerItem(284, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btn_barre_accetta = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_barre_accetta.sizePolicy().hasHeightForWidth())
        self.btn_barre_accetta.setSizePolicy(sizePolicy)
        self.btn_barre_accetta.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_barre_accetta.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_barre_accetta.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"")
        self.btn_barre_accetta.setText("")
        self.btn_barre_accetta.setIcon(icon3)
        self.btn_barre_accetta.setIconSize(QtCore.QSize(30, 30))
        self.btn_barre_accetta.setObjectName("btn_barre_accetta")
        self.horizontalLayout_6.addWidget(self.btn_barre_accetta)
        self.btn_barre_cancella = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_barre_cancella.sizePolicy().hasHeightForWidth())
        self.btn_barre_cancella.setSizePolicy(sizePolicy)
        self.btn_barre_cancella.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_barre_cancella.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_barre_cancella.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"")
        self.btn_barre_cancella.setText("")
        self.btn_barre_cancella.setIcon(icon4)
        self.btn_barre_cancella.setIconSize(QtCore.QSize(32, 32))
        self.btn_barre_cancella.setObjectName("btn_barre_cancella")
        self.horizontalLayout_6.addWidget(self.btn_barre_cancella)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.tableView_barre = QtWidgets.QTableView(self.frame_barre)
        self.tableView_barre.setMinimumSize(QtCore.QSize(0, 450))
        self.tableView_barre.setMaximumSize(QtCore.QSize(16777215, 450))
        self.tableView_barre.setStyleSheet("background-color: rgb(35,35,35);\n"
"border-radius:4px")
        self.tableView_barre.setObjectName("tableView_barre")
        self.verticalLayout_2.addWidget(self.tableView_barre)
        self.verticalLayout_sezione.addWidget(self.frame_barre)
        self.btn_sezioni_rinforzi = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_sezioni_rinforzi.setMinimumSize(QtCore.QSize(100, 32))
        self.btn_sezioni_rinforzi.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_sezioni_rinforzi.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    font:400 12pt \"Segoe UI\";\n"
"    color: rgb(255,255,255);\n"
"    padding-bottom: 4px;\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(50,50,50);\n"
"}\n"
"")
        self.btn_sezioni_rinforzi.setObjectName("btn_sezioni_rinforzi")
        self.verticalLayout_sezione.addWidget(self.btn_sezioni_rinforzi)
        self.frame_rinforzi = QtWidgets.QFrame(self.layoutWidget)
        self.frame_rinforzi.setStyleSheet("background-color: rgb(40,40,40);\n"
"border-radius:4px")
        self.frame_rinforzi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rinforzi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rinforzi.setObjectName("frame_rinforzi")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_rinforzi)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_rinforzi)
        self.frame_6.setStyleSheet("background-color: rgb(30,30,30);\n"
"border-radius:4px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_22.setStyleSheet("font:400 12pt \"Segoe UI\";\n"
"color: rgb(255,255,255);\n"
"border: none")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.btn_rinforzi_disegna = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rinforzi_disegna.sizePolicy().hasHeightForWidth())
        self.btn_rinforzi_disegna.setSizePolicy(sizePolicy)
        self.btn_rinforzi_disegna.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_rinforzi_disegna.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_rinforzi_disegna.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(40,40,40);\n"
"}\n"
"")
        self.btn_rinforzi_disegna.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("interfaccia\\icone/rinforzo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rinforzi_disegna.setIcon(icon7)
        self.btn_rinforzi_disegna.setIconSize(QtCore.QSize(40, 40))
        self.btn_rinforzi_disegna.setObjectName("btn_rinforzi_disegna")
        self.horizontalLayout_8.addWidget(self.btn_rinforzi_disegna)
        spacerItem2 = QtWidgets.QSpacerItem(284, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.btn_rinforzi_accetta = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rinforzi_accetta.sizePolicy().hasHeightForWidth())
        self.btn_rinforzi_accetta.setSizePolicy(sizePolicy)
        self.btn_rinforzi_accetta.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_rinforzi_accetta.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_rinforzi_accetta.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"")
        self.btn_rinforzi_accetta.setText("")
        self.btn_rinforzi_accetta.setIcon(icon3)
        self.btn_rinforzi_accetta.setIconSize(QtCore.QSize(30, 30))
        self.btn_rinforzi_accetta.setObjectName("btn_rinforzi_accetta")
        self.horizontalLayout_8.addWidget(self.btn_rinforzi_accetta)
        self.btn_rinforzi_cancella = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rinforzi_cancella.sizePolicy().hasHeightForWidth())
        self.btn_rinforzi_cancella.setSizePolicy(sizePolicy)
        self.btn_rinforzi_cancella.setMinimumSize(QtCore.QSize(45, 40))
        self.btn_rinforzi_cancella.setMaximumSize(QtCore.QSize(45, 40))
        self.btn_rinforzi_cancella.setStyleSheet("QPushButton{\n"
"    border-radius:4px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px solid rgb(120,120,120);\n"
"}\n"
"")
        self.btn_rinforzi_cancella.setText("")
        self.btn_rinforzi_cancella.setIcon(icon4)
        self.btn_rinforzi_cancella.setIconSize(QtCore.QSize(32, 32))
        self.btn_rinforzi_cancella.setObjectName("btn_rinforzi_cancella")
        self.horizontalLayout_8.addWidget(self.btn_rinforzi_cancella)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.tableView_rinforzi = QtWidgets.QTableView(self.frame_rinforzi)
        self.tableView_rinforzi.setMinimumSize(QtCore.QSize(0, 300))
        self.tableView_rinforzi.setMaximumSize(QtCore.QSize(16777215, 300))
        self.tableView_rinforzi.setStyleSheet("background-color: rgb(35,35,35);\n"
"border-radius:4px")
        self.tableView_rinforzi.setObjectName("tableView_rinforzi")
        self.verticalLayout_3.addWidget(self.tableView_rinforzi)
        self.verticalLayout_sezione.addWidget(self.frame_rinforzi)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_sezioni_sezione.setText(_translate("Form", "SEZIONE"))
        self.label_20.setText(_translate("Form", " Forma:"))
        self.btn_sezioni_barre.setText(_translate("Form", "BARRE"))
        self.label_21.setText(_translate("Form", " Tipologia:"))
        self.btn_sezioni_rinforzi.setText(_translate("Form", "RINFORZI"))
        self.label_22.setText(_translate("Form", " Tipologia:"))
